using System.ComponentModel.DataAnnotations;

namespace BetclicApi.Models;

/// <summary>
/// Represents a user in the system.
/// </summary>
public class User
{
    /// <summary>
    /// A unique identifier generated by the system
    /// </summary>
    public long Id { get; set; }
    
    /// <summary>
    /// The username of the user. The username must be between 3 and 30 characters.
    /// </summary>
    [Required]
    [StringLength(30, MinimumLength = 3, ErrorMessage = "Username must be between 3 and 30 characters.")]
    public string Username { get; set; } = string.Empty;
    
    /// <summary>
    /// The points accumulated by the user so far.
    /// </summary>
    public int Points { get; set; }
    
    
    /// <summary>
    /// The user's rank in the tournament. Computed on request and not stored in the database.
    /// </summary>
    public uint Rank { get; set; }
}